from enum import Enum

class GameMode(Enum):
    ADVENTURE = 1
    SURVIVAL = 2

SCREEN_WIDTH = 384
SCREEN_HEIGHT = 272

ADVENTURE_ZONES = 5
SLIMES_PER_ZONE = 3
ZONE_BOSS_DIFFICULTY = 1.5

SURVIVAL_START_DIFFICULTY = 1.0
SURVIVAL_DIFFICULTY_INCREMENT = 0.1

GAME_FPS = 10
