"""
Catalogue des slimes pour VEX Numwork
"""

SLIMES = {
    "slime_001": {
        "nom": "Gelée Commune",
        "rarete": "Commun",
        "emoji": "🟢",
        "zone": 1,
        "hp": 20,
        "atk": 10,
        "def": 5,
        "vit": 8,
        "xp": 10,
        "chance_capture": 0.6,
    },
    "slime_002": {
        "nom": "Blob Bleu",
        "rarete": "Commun",
        "emoji": "🔵",
        "zone": 1,
        "hp": 22,
        "atk": 11,
        "def": 6,
        "vit": 7,
        "xp": 11,
        "chance_capture": 0.65,
    },
    "slime_003": {
        "nom": "Essence Pourpre",
        "rarete": "Rare",
        "emoji": "🟣",
        "zone": 2,
        "hp": 30,
        "atk": 15,
        "def": 8,
        "vit": 10,
        "xp": 25,
        "chance_capture": 0.5,
    },
    "slime_004": {
        "nom": "Cristal Rose",
        "rarete": "Rare",
        "emoji": "💎",
        "zone": 2,
        "hp": 28,
        "atk": 14,
        "def": 9,
        "vit": 9,
        "xp": 24,
        "chance_capture": 0.55,
    },
    "slime_005": {
        "nom": "Gélatine d'Or",
        "rarete": "Épique",
        "emoji": "🟡",
        "zone": 3,
        "hp": 40,
        "atk": 20,
        "def": 12,
        "vit": 12,
        "xp": 50,
        "chance_capture": 0.4,
    },
    "slime_006": {
        "nom": "Blob Ombre",
        "rarete": "Épique",
        "emoji": "⚫",
        "zone": 3,
        "hp": 42,
        "atk": 21,
        "def": 11,
        "vit": 11,
        "xp": 52,
        "chance_capture": 0.42,
    },
    "slime_007": {
        "nom": "Masse Écarlate",
        "rarete": "Légendaire",
        "emoji": "🔴",
        "zone": 4,
        "hp": 60,
        "atk": 30,
        "def": 15,
        "vit": 14,
        "xp": 100,
        "chance_capture": 0.2,
    },
    "slime_008": {
        "nom": "Prisme Blanc",
        "rarete": "Légendaire",
        "emoji": "⚪",
        "zone": 4,
        "hp": 58,
        "atk": 28,
        "def": 16,
        "vit": 13,
        "xp": 95,
        "chance_capture": 0.25,
    },
    "slime_009": {
        "nom": "Abysse Primordiale",
        "rarete": "Mythique",
        "emoji": "🖤",
        "zone": 5,
        "hp": 100,
        "atk": 50,
        "def": 25,
        "vit": 20,
        "xp": 200,
        "chance_capture": 0.05,
    },
}

ZONE_BOSSES = {
    1: "slime_001",
    2: "slime_003",
    3: "slime_005",
    4: "slime_007",
    5: "slime_009",
}
